%% Stepper Motor Pull-in Characteristics 
% 
% This example shows how to parameterize and tune a stepper motor using manufacturer datasheet
% information and a test harness. The model is parameterized using numerical 
% data extracted from a datasheet. The simulation generates pull-in torque
% characteristics that you can compare to a manufacturer-provided pull-in curve.
% To tune the stepper motor model, the example uses a test harness that varies 
% the drive type and load parameters. 
%

% Copyright 2019-2023 The MathWorks, Inc.


%% Test Harness
% The stepper is modeled using the Stepper Motor block from the Simscape(TM) 
% Electrical(TM) library. The stepper motor driver is modelled by a current source 
% and a first order filter. The motor is placed in a test harness. The test 
% harness gradually increases the load until slip occurs for each step rate demand 
% tested. Slip detection is implemented in the Slip Detection subsystem.
% The subsystem contains a Simulink(R) assertion block that determines the difference 
% between expected and actual rotor angle.
StepperMotorPullInData;
open_system(modelFileName)
set_param(find_system(modelFileName,'FindAll', 'on','type','annotation','Tag','ModelFeatures'),'Interpreter','off')

%% Pull-in Torque Characteristics
% The plot shows the pull-in characteristics generated by the test harness
% simulation. Results are superimposed on the pull-in curve from the manufacturer 
% datasheet. Achieving an exact match for the pull-in characteristics can be
% challenging because most datasheets do not specify the test conditions. 
% Furthermore, some datasheets do not provide all the numerical values required 
% to model the stepper motor. In this case, the pull-in curve from the simulation 
% is used to determine for representative values that yield an acceptable
% pull-in curve match.
StepperMotorPullInPlot;

%% Pull-in Characteristics Sensitivity to Drive and Load Parameters
% In pull-in mode, a stepper motor must start and stop without losing synchronization.
% Due to the dynamic nature of stepper motors, pull-in torque-speed performance 
% is highly sensitive to stepper motor drive configuration and load parameters. 
% 
% When modeling or tuning a stepper motor, consider that:
%
% * Increasing the load inertia reduces the stepper motor pull-in torque at 
% higher step rates. Generally, for high step-rate operation, load inertia 
% is less than three times that of rotor inertia. It is a generally-accepted 
% practice to limit the load inertia to less than ten times that of rotor inertia.
% * Loads with higher damping component results in better performance at lower
% step rates because damping helps to overcome the effects of stepper motor 
% resonance. Similarly, internal motor rotor damping can also help to improve 
% the performance at low step rates.
% * Stepper motors with low winding resistance are often driven using a constant
% current drive. To reduce the current rise time, higher than the rated 
% voltage is applied to the motor. The higher supply voltage yields higher pull-in torque 
% capability at higher step rates.
% * Pull-in torque curve provided on a manufacturer datasheet is typically 
% given for a particular driver and load configuration (load type, load inertia and
% load damping). Manufacturers tend to test stepper motors either with a dyno 
% setup or by applying friction to the rotor wheel. The test method is rarely 
% included on the data sheet. Therefore, it is always important to simulate the 
% stepper motor to generate the curve for parameterization validation purposes.
%
% The plot shows how the pull-in torque is sensitive to rotor damping, drive voltage, 
% load inertia, and load type.

figure;
imshow('StepperMotorPullInSensitivity.png');
%%
% For any given stepper motor, the set of model parameter values that matches
% the pull-in torque characteristics is not typically unique. To ensure the 
% parameterization is representative, it is good practice to also generate 
% and compare the pull-out curve with the datasheet.

%%

